### ISSUE TITLE
怎么实现上拉加载更多数据

### ISSUE THREAD

**Issue by LCBbest** [kuan1/kuan-vue-waterfall#11]
自己写的上拉加载更多数据，会在底部无限加载。不是网络请求原因，而是请求结束之后 图片还未显示，dom没有更新，导致一直在底部，所以无限出发上拉加载。

**Comment by kuan1** [comment]
> 自己写的上拉加载更多数据，会在底部无限加载。不是网络请求原因，而是请求结束之后 图片还未显示，dom没有更新，导致一直在底部，所以无限出发上拉加载。

我没有太明白你的意思，你的意思是你在写加载更多的时候拉取接口会不停的触发？你可以在请求接口的时候加一个状态，接口返回情况这个状态，保证一次只有一个接口在执行
