### ISSUE TITLE
你好啊，咋把下面的文字去掉，或者有啥属性提供定义吗

### ISSUE THREAD

**Issue by aion1998** [kuan1/kuan-vue-waterfall#12]
![image](https://user-images.githubusercontent.com/19725014/119236783-e0a90480-bb6b-11eb-823b-ecdf58097f4f.png)
如图这样

**Comment by kuan1** [comment]
> ![image](https://user-images.githubusercontent.com/19725014/119236783-e0a90480-bb6b-11eb-823b-ecdf58097f4f.png)
> 如图这样

去掉下边的代码就行了
```html
<p>{{ item.src }}</p>
```
