### ISSUE TITLE
使用vite构建生产环境包成功打包后 运行资源文件 插件报错

### ISSUE THREAD

**Issue by xiaojueji** [kuan1/kuan-vue-waterfall#17]
报错提示为：` Cannot read property 'refs' of null`
可以确认时插件报错的 因为去掉插件引用 再次打包后运行就不会报错
![image](https://user-images.githubusercontent.com/31124354/122668041-dae52400-d1e8-11eb-85c1-8d67e6fb88f9.png)

**Comment by xiaojueji** [comment]
版本号如下：
node：14.15.0
vite: "^2.3.4"
vue: "^3.0.5",
vue-router: "4",
vuex: "^4.0.1"
kuan-vue-waterfall: "^3.0.1",

**Comment by xiaojueji** [comment]
mac 系统：11.2.3
浏览器版本：chrome  91.0.4472.106（正式版本） (x86_64)

**Comment by kuan1** [comment]
@xiaojueji, 这个问题说不太好。你可以尝试把当前仓库的src作为一个组件放在你的项目中，测试一下打包后是不是还有问题？
