### ISSUE TITLE
容器宽度获取问题

### ISSUE THREAD

**Issue by 6xiaowu9** [kuan1/kuan-vue-waterfall#22]
我在使用dialog的时候发现容器宽度获取出现获取到0的问题，需要nextTick后才能获取到真实宽度，我进行了合并请求，不知道搞得对不对，麻烦辛苦看一下，谢谢 @kuan1

**Comment by kuan1** [comment]
@6xiaowu9 单个容器的高度，在`water-fall-item`中的`mounted`钩子中通过clientHeight获取的。如果组件初始化的时候`display:none`会有问题，或者搜索其他比较稳定的组件，毕竟这个组件没有做太多的测试 -。-

**Comment by kuan1** [comment]
@6xiaowu9 因为`mounted`是dom插入之后的钩子，再加入`nextTick`有些奇怪，有复现的demo的吗，我看下

**Comment by 6xiaowu9** [comment]
是宽度，我写在dialog内就会出现这个问题

**Comment by kuan1** [comment]
@6xiaowu9 我合并了你的commit
